[#166185743] Allow managers deactivate trainers from a gym
andela/wger-kronos pull request #25
Opened 2019-06-17 12:25 UTC by Rhytah

#### What does this PR do?
Allow managers deactivate trainers from a gym

#### Description of Task to be completed?

- [ ] Have the username in gym member list as a link to the user's details

#### How should this be manually tested?

#### Any background context you want to provide?
Currently, a manager cannot delete or deactivate trainers from a gym.

They should be able to do this

#### What are the relevant pivotal tracker stories?
[#166185743](https://www.pivotaltracker.com/story/show/166185743)

2019-06-19 10:00 UTC, reifred approved these changes
Thanks, @Rhytah for the work done. The feature is working as described.

2019-06-19 10:00 UTC, reifred commented on .travis.yml
>    - if [[ "$DB" = "postgresq" ]]; then psql -c 'DROP DATABASE IF EXISTS test_wger;' -U postgres; fi
This will surely fix the gulp install error on travis

2019-06-19 11:24 UTC, Manorlds-Eaglespark approved these changes

2019-06-19 12:06 UTC, Emmanuel-Dominic approved these changes

2019-06-19 13:05 UTC, Emmanuel-Dominic requested changes
Great work @Rhytah, thanks for the work

2019-06-19 13:07 UTC, Emmanuel-Dominic approved these changes

2019-06-20 07:07 UTC, AGMETEOR commented
@Rhytah in your PR description under `What does this PR do?` there's some more information missing about what was implemented by this code.

2019-06-20 07:33 UTC, Rhytah commented
> @Rhytah in your PR description under `What does this PR do?` there's some more information missing about what was implemented by this code.

@AGMETEOR  do you mean the added `status` of a user in the table or the `migrations`? Or should I include everything?

2019-06-20 07:37 UTC, AGMETEOR commented
@Rhytah the story also says "delete" trainers.

2019-06-20 07:40 UTC, AGMETEOR commented
@Rhytah I am going to request that you separate out the task on`Update travis.yml to fix gulp errors in Travis Build.` into a different PR whose merge we're going to prioritize.

2019-06-20 07:41 UTC, AGMETEOR commented on .travis.yml
>    - if [[ "$DB" = "postgresq" ]]; then psql -c 'DROP DATABASE IF EXISTS test_wger;' -U postgres; fi
@Rhytah put into a different PR.

2019-06-20 07:51 UTC, Rhytah commented
> @Rhytah the story also says "delete" trainers.

@AGMETEOR I have added this.

2019-06-20 07:51 UTC, Rhytah commented
> @Rhytah I am going to request that you separate out the task on`Update travis.yml to fix gulp errors in Travis Build.` into a different PR whose merge we're going to prioritize.

@AGMETEOR on it.

2019-06-21 08:45 UTC, merged