#166239312 Set up Heroku deployment
andela/wger-kronos pull request #4
Opened 2019-05-27 13:25 UTC by Emmanuel-Dominic

#### What does this PR do?
 - This helps in manifest format for describing web apps.

#### Description of Task to be completed?
 - This has an app.json file that declares environment variables, add-ons, and other information required to run an app on Heroku.

#### What are the relevant pivotal tracker stories?
- #166239312

2019-05-27 14:39 UTC, Rhytah commented
@Emmanuel-Dominic  could you consider editing the PR description, especially `What does this PR do?` to be more specific to the story scope of the task at hand.

2019-05-28 07:56 UTC, reifred requested changes
Thanks for the work done @Emmanuel-Dominic, kindly include the links in the PR description for us to test the deployments you have set up. In addition, make your story id linkable to pivotal tracker.

2019-05-28 08:26 UTC, Manorlds-Eaglespark reviewed
Thanks for this great work so far, however, to approve your changes, I will wait till all the tests are passing on Travis.

2019-05-28 09:40 UTC, AGMETEOR commented
@Emmanuel-Dominic change the description to try and match the story description on the PT Board. Also, link the story id to the PT story.

2019-05-29 13:09 UTC, AGMETEOR commented on settings.py
> +# }
Is this commented out code necessary?

2019-05-30 14:48 UTC, closed without merging